default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>

development:
  <<: *default
  database: active_record_date_validator_development

test:
  <<: *default
  database: active_record_date_validator_test

production:
  <<: *default
  database: active_record_date_validator_production
