name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      # Install dependencies
      - name: Install Dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install

      # Run the tests
      - name: Run Tests
        run: |
          bundle exec rspec
