name: Ruby CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'
          bundler-cache: false  # Disable auto-caching to customize

      # Step 3: Install system dependencies for common gems (like pg and openssl)
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libpq-dev build-essential

      # Step 4: Install Compatible RubyGems and Bundler
      - name: Update RubyGems and Install Bundler
        run: |
          gem install rubygems-update -v '<= 3.4.13'
          update_rubygems
          gem install bundler
          bundle -v

      # Step 5: Cache Gem Dependencies (customized)
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: setup-ruby-bundler-cache-v6-${{ runner.os }}-ruby-2.7.8-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            setup-ruby-bundler-cache-v6-${{ runner.os }}-ruby-2.7.8-

      # Step 6: Install dependencies
      - name: Install Dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      # Step 7: Run tests
      - name: Run Tests
        run: bundle exec rspec

      # Step 8: Print Environment Variables (for debugging)
      - name: Print Environment
        run: env
